name: mindquan
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.1.0.77=h90431f1_0
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipython=7.33.0=py37h89c1867_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.48.0=hee588c1_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.4.1=h7b32b05_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - prompt-toolkit=3.0.48=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - readline=8.2=h8228510_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.48.0=h9eae976_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.2=py37h540881e_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zeromq=4.3.5=h75354e8_4
  - pip:
    - absl-py==2.1.0
    - anyio==3.7.1
    - astor==0.8.1
    - asttokens==2.4.1
    - astunparse==1.6.3
    - autograd==1.6.2
    - backports-cached-property==1.0.2
    - certifi==2024.12.14
    - charset-normalizer==3.3.2
    - cirq-core==1.1.0
    - colorama==0.4.6
    - commonmark==0.9.1
    - cycler==0.11.0
    - deprecation==2.1.0
    - dill==0.3.7
    - duet==0.2.8
    - exceptiongroup==1.2.1
    - filelock==3.12.2
    - fonttools==4.38.0
    - future==1.0.0
    - h11==0.14.0
    - h5py==3.8.0
    - httpcore==0.17.3
    - httpx==0.24.1
    - idna==3.7
    - imageio==2.31.2
    - importlib-metadata==4.8.1
    - iniconfig==2.0.0
    - jax==0.2.10
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - llvmlite==0.36.0
    - matplotlib==3.5.3
    - mindquantum==0.9.0
    - mindspore==2.2.14
    - mpi4py==3.1.4
    - mpmath==1.3.0
    - multiprocess==0.70.15
    - networkx==2.6.3
    - numba==0.53.1
    - numpy==1.21.6
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - ofpp==0.1
    - opencv-python==4.10.0.84
    - openfermion==1.6.1
    - openfermionpyscf==0.5
    - opt-einsum==3.3.0
    - packaging==24.0
    - paddlepaddle==0.0.0
    - pandas==1.3.5
    - pathos==0.3.1
    - pillow==9.5.0
    - pip==24.0
    - pluggy==1.2.0
    - pox==0.3.3
    - ppft==1.7.6.7
    - protobuf==4.24.4
    - psutil==6.0.0
    - pubchempy==1.0.4
    - pyaml==23.5.8
    - pydoe==0.3.8
    - pyparsing==3.1.2
    - pyscf==2.6.2
    - pytest==7.4.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - requests==2.31.0
    - rich==10.9.0
    - sciai==0.1.0
    - scikit-learn==1.0.2
    - scikit-optimize==0.10.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - setuptools==68.0.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - sympy==1.10.1
    - threadpoolctl==3.1.0
    - tikzplotlib==0.10.1
    - tomli==2.0.1
    - tqdm==4.66.4
    - typing-extensions==3.10.0.2
    - uncertainties==3.1.7
    - urllib3==2.0.7
    - webcolors==1.13
    - zipp==3.15.0